### ISSUE TITLE
Full Support for MySQL BIGINT

### ISSUE THREAD

**Issue by vlasky** [nevill/zongji#108]
Native JavaScript BigInt support was added to Node.js 10.4. This means that Zongji can now provide complete support for MySQL BIGINTs.

At the moment, [the docs warn that](https://github.com/nevill/zongji#important-notes):

> While 64-bit integers in MySQL (BIGINT type) allow values in the range of 264 (± ½ × 264 for signed values), Javascript's internal storage of numbers limits values to 253, making the allowed range of BIGINT fields only -9007199254740992 to 9007199254740992. Unsigned 64-bit integers must also not exceed 9007199254740992.

I suggest that zongi use the [BigInteger.js module](https://github.com/peterolson/BigInteger.js/) which operates as polyfill for versions of Node.js prior to 10.4, otherwise it works as a thin wrapper around the native JavaScript BigInt.

**Comment by nevill** [comment]
We were thinking of using package [Long](https://www.npmjs.com/package/long), seems `BigInteger.js` is a better alternative.
