### ISSUE TITLE
[question] why did I follow the installation but report error?

### ISSUE THREAD

**Issue by wuxianliang** [nevill/zongji#11]
Dear @nevill 

I am using mac with mysql 5.6. When I finish the second step -- modifying my.cnf. 
Error Reporting:
```
Starting MySQL
. ERROR! The server quit without updating PID file (/usr/local/mysql/data/NiTu.pid).
```
when I delete these new lines, Mysql works again.

How to fix it? 

By the way, I am trying to understand meteor-mysql for developing the meteor-orientdb and I opened an issue here. https://github.com/orientechnologies/orientdb/issues/3602 

Wish you can do me a favor. Do we have to reproduce zongji for OrientDB?

Thank you very much!
新春快乐！

**Comment by wuxianliang** [comment]
I have fixed this problem by changing
```
log_bin          = /usr/local/var/log/mysql/mysql-bin.log
```
to 
```
log-bin          = mysql-bin
```

**Comment by nevill** [comment]
@wuxianliang I have no idea about `OrientDB`, seems it has replication support. But, I guess the protocol is totally different from MySQL. Why not build it yourself, if you want to have a similar tool to `OrientDB` as `ZongJi` to MySQL :smiling_imp:

**Comment by numtel** [comment]
@wuxianliang @nevill Readme updated with the a path that makes more sense for `log_bin` (it's the default on Ubuntu)

**Comment by wuxianliang** [comment]
Thank you @numtel .

@nevill I am a primary school teacher, coding apps for education in spare time. Recently, I think maybe I can do more than just using packages. It is good if we can SQL all three kinds of data. But I do not have ability and time to dive into databases. So I am following numtel 's structure and dimitru 's way to handle events. Hope I can succeed.
