### ISSUE TITLE
How to remove event listener?

### ISSUE THREAD

**Issue by ekoeryanto** [nevill/zongji#114]
Is there a way to remove a listener?
such as
```
zongji.on('binlog', () => {})

zongji.removeEventListener(...)
```

thanks

**Comment by nevill** [comment]
Sure, as simple as [removeListener](https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_emitter_removelistener_eventname_listener).

**Comment by ekoeryanto** [comment]
something silly from me, there is a sample from the `example`
