### ISSUE TITLE
is there has any chinese document？

### ISSUE THREAD

**Issue by liuxingpluck** [nevill/zongji#127]
有没有中文文档呢？我最近有个需求 需要对 数据库的binlog 做监控，可是 看到 zongji.on('binlog', function (evt) {}) 有点蒙，不知道 evt 的构成 和属性

**Comment by nevill** [comment]
目前没有任何中文文档。
如果你的业务需要我可以提供咨询服务，联系方式可以通过代码提交中的信息得到我的邮箱。
