### ISSUE TITLE
Need help maintaining this library?

### ISSUE THREAD

**Issue by jefbarn** [nevill/zongji#132]
@nevill Haven't gotten a release in over a year, and quite a few PRs stacked up. Do you wan't some help maintaining this library?

**Comment by nevill** [comment]
Hi @jefbarn, glad to hear from you.
Indeed, I am busy with something else now. It would be cool if someone can help. I'd like to have some introduction of yourself first, if you want to involve.
Also, I opened [discussions](https://github.com/nevill/zongji/discussions) of this repo, maybe we can continue on it there.
