### ISSUE TITLE
是否有详细的压测报告呢？

### ISSUE THREAD

**Issue by xiexiaodong** [nevill/zongji#18]

**Comment by nevill** [comment]
@xiexiaodong Sorry, we don't have any kind of report, this is only a npm package, you can use it for any purpose, including any tests you want.

**Comment by xiexiaodong** [comment]
Now I would like to ask this tool has been used in the environment?

**Comment by nevill** [comment]
Sorry, there is not any kind of tool like that in this package. :santa: You can try any kind of tool with this package in your environment, and welcome to share your report.

**Comment by numtel** [comment]
I don't read Chinese but Google translates the title as "Is there a detailed pressure measurement report it". I'm guessing you are inquiring about performance statistics?

@vlasky has been using this package through my mysql-live-select NPM package and numtel:mysql Meteor package in an environment with high loads. Maybe he will chime in about his experiences. 

When writing the remainder of the field decoders, I focused on completion, not performance. If you would like help analyzing and possibly improving the performance of this package, please send me an email. I am available for contract work at the moment.

**Comment by xiexiaodong** [comment]
@numtel Thank you I am currently working in Alibaba, engaged in the development of data layer middleware. In the process of improving the product, want to see if nodejs is better than Java in this regard whether there is a place worth learning. If there is a chance I would like to participate in

**Comment by nevill** [comment]
@numtel You mean @vlasky has been using it in a production(more or less) environment? I also want to have some feedback.
