### ISSUE TITLE
We need a uniform code style in case more PRs coming

### ISSUE THREAD

**Issue by nevill** [nevill/zongji#23]
I created a branch named [when-PR-coming](https://github.com/nevill/zongji/tree/when-PR-coming) to fix all the code style issue here.

Advice is welcome before I have this branch merged. :smiling_imp:

**Comment by p-j** [comment]
If I may, I'd suggest [standardjs](http://standardjs.com/) which comes with both a linter and a formater, no need for configuration files other than `package.json` and a shiny badge for your readme.

If you'd rather use other style rules (semicolons, tabs ... ) you can check the [ecosystem](http://standardjs.com/awesome.html#forks) which has plenty of variations, eventhough the whole point of `standard` was to avoid the headhake of establishing rules and debating them.
