### ISSUE TITLE
Running on Amazon RDS for MySQL

### ISSUE THREAD

**Issue by mrn3** [nevill/zongji#30]
Will this work on RDS?  I am trying to make it work, but it complains that my user doesn't have replication client privilege, and I don't think you can grant a user that role on RDS.

**Comment by nevill** [comment]
Interesting, never thought of a scenario like this. But looks like AWS has an CreateDBInstanceReadReplica API for that, check [with it here](https://aws.amazon.com/rds/faqs/#read-replicas).
According to [MySQL on Amazon RDS](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html)
> When you create an Amazon RDS DB instance, the master user has the following default privileges:
...
replication client
replication slave (MySQL 5.6 and later)
...

Hope it helps.

**Comment by mrn3** [comment]
Great thanks - will check that out
