### ISSUE TITLE
Working on node 4.3?

### ISSUE THREAD

**Issue by mrn3** [nevill/zongji#32]
When I do npm install, I see:

WARN engine zongji@0.3.2: wanted: {"node":"0.10"} (current: {"node":"4.3.1","npm":"2.14.12"})

Will zongji work on node 4.3?  Will it be upgraded soon?

**Comment by numtel** [comment]
It should work fine. The automated tests on Travis CI run on 4.2. That line should be updated.

**Comment by mrn3** [comment]
Okay thanks - so are you saying if that line is updated, npm will stop complaining with the warning?  It would be nice to get rid of the warning.

**Comment by jmealo** [comment]
@mrn3 I just bumped the dependencies on my fork which has some improvements if you want to give it a shot: https://github.com/jmealo/zongji

**Comment by nevill** [comment]
If possible, I would like to know what is the majority version of node.js used in production environment. As far as I can tell, we are still using 0.10 (even some are 0.8) in production. Also, I noticed that CentOS / RHEL is still using 0.10 in official package repository. Any clues?

**Comment by jmealo** [comment]
I've been running the latest 4.x release in production for 2-3 months on Ubuntu 14.04 (64-bit).

**Comment by mrn3** [comment]
I have been using node 4.3.1 in production on CentOS without issues for a month or so.
