### ISSUE TITLE
Once started, setting options 'includeSchema' has no expected behaviour

### ISSUE THREAD

**Issue by dtrigo** [nevill/zongji#38]
Once the table is maped (after listening an table event) the rows event is always fired...

trace it to /lib/rows_event.js L:41 added the OR statement fixes this issue, but I'm not sure it it's the right place to do it

if(tableData === undefined 
    || zongji._skipSchema(tableData.parentSchema, tableData.tableName)){
    // TableMap event was filtered
    parser._offset = parser._packetEnd;
    this._filtered = true;

**Comment by numtel** [comment]
Thanks for the issue.
