### ISSUE TITLE
Completing the remaining fields

### ISSUE THREAD

**Issue by numtel** [nevill/zongji#4]
This project seems like it's going to be very useful for my project to bring "reactive" MySQL select statements to the Meteor framework (see my [meteor-mysql repository](https://github.com/numtel/meteor-mysql)).

I have begun working on getting the remaining fields handled as well as getting a test suite started. Please view my progress on this branch:

https://github.com/numtel/zongji/tree/more_fields

I've updated the readme with a table showing each field's status as well as instructions for getting the tests running.

* Do you have any thoughts on progress?
* Want one big PR or many small ones?
* After the remaining fields are integrated, is there anything else keeping this rewrite from a 0.3.0 release?

**Comment by nevill** [comment]
Closing this one, thanks for your effort @numtel
