### ISSUE TITLE
Make it possible to restart ZongJi on error

### ISSUE THREAD

**Issue by numtel** [nevill/zongji#45]
In https://github.com/nevill/zongji/pull/41#issuecomment-223051552, I have suggested a method of making it possible to recover from errors and disconnections.

- [x] Make it possible to determine the current binlog filename
  * Currently, [`findBinlogEnd`](https://github.com/nevill/zongji/blob/master/index.js#L62) only determines the filename if the `startAtEnd` option is `true`. Otherwise, that value is an empty string. Either way, this value is not externally available the way the code is right now.
  * Binlog position is available as [a property of each event](https://github.com/nevill/zongji/blob/master/lib/binlog_event.js#L6). It seems like the optimal patch would simply add a property for the current binlog file name.
- [x] Make it possible to start reading binlog events from a specific filename and position
   * Will have to create configuration options that modify the [`binlogOptions` object](https://github.com/nevill/zongji/blob/master/index.js#L90)

I'm not sure how much time I'll get to work on this soon so if anybody wants to help look into what it will take to do this, that would be awesome.

**Comment by numtel** [comment]
To get the current binlog filename, it looks like the `ctrlConnection` could be used to run a [`SHOW SLAVE STATUS`](https://dev.mysql.com/doc/refman/5.6/en/show-slave-status.html) query but in order for ZongJi replication clients to show up on this list, they must send the [`COM_REGISTER_SLAVE`](https://dev.mysql.com/doc/internals/en/com-register-slave.html) packet before the `COM_BINLOG_DUMP` packet.

[In this commit, I have created tried to send this packet](https://github.com/nevill/zongji/commit/93673335c55cc2af81b2d2598dbf03850357069c) but it causes this error. The `COM_REGISTER_SLAVE` one sends without causing an error but the original `COM_BINLOG_DUMP` causes this error when that `COM_REGISTER_SLAVE` has been sent.

```
Error: Packets out of order. Got: 1 Expected: 2
    at Parser.write (/vagrant/zongji/node_modules/mysql/lib/protocol/Parser.js:39:19)
    at Protocol.write (/vagrant/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/vagrant/zongji/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
    --------------------
    at Protocol._enqueue (/vagrant/zongji/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Immediate._start [as _onImmediate] (/vagrant/zongji/index.js:203:31)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

I tried putting [these lines](https://github.com/nevill/zongji/blob/93673335c55cc2af81b2d2598dbf03850357069c/lib/packet/comregisterslave.js#L10-17) directly into the top of the `combinlog` write function so that it would send both packets simultaneously. This did not work.

I found a Go project that connects to MySQL as a replication slave but I can't figure out what it is doing differently to register the slave and dump the binlog correctly. [Initializing the `binlogsyncer`](https://github.com/siddontang/go-mysql/blob/1a1e7fd11cb6e2d7034f903a2a8b62c8aa47a170/cmd/go-mysqlbinlog/main.go), and [the `binlogsyncer` implementation](https://github.com/siddontang/go-mysql/blob/1a1e7fd11cb6e2d7034f903a2a8b62c8aa47a170/replication/binlogsyncer.go).

@nevill Any idea how to get this packet sent properly?

**Comment by numtel** [comment]
[Creating a separate Sequence subclass for the `comregisterslave` packet](https://github.com/nevill/zongji/commit/efe78fdb0ecba785188243e9c62019d039ac04c5) waits for the `OkPacket` before sending the `combinlog` packet. This works but I still do not have any results:

```
mysql> show slave status;
Empty set (0.00 sec)
```

I think I was wrong about how to use that command. It seems it is to be executed on a MySQL server instance that is currently replicating, not the master server. Due to this, another path for determining the current binlog filename must be sought.

**Comment by numtel** [comment]
See https://github.com/nevill/zongji/pull/49

**Comment by shtse8** [comment]
I still getting `The server closed the connection.` for the latest version, any way to restart ZongJi once error?

**Comment by subhasisghosal** [comment]
I'm having the following error:

Error: ER_MASTER_FATAL_ERROR_READING_BINLOG: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event '' at 4, the last event read from '/rdsdbdata/log/binlog/mysql-bin-changelog.001679' at 422, the last byte read from '/rdsdbdata/log/binlog/mysql-bin-changelog.001679' at 422.
