### ISSUE TITLE
Not parsing Double (IEEE754) correctly?

### ISSUE THREAD

**Issue by jefbarn** [nevill/zongji#54]
I'm getting back 1.1125369292536007e-308 instead of 0 from zongji for all my Double fields.
Perhaps a problem with parsing subnormal numbers?

**Comment by Legion102** [comment]
The same problem, can we expect this issue to be fixed?

**Comment by Legion102** [comment]
This issue occurs only with "0" value. I don't use such small numbers as `1.1125369292536007e-308`. So, as a temporary solution I resolve the issue this way:
`if(row[key]==1.1125369292536007e-308){
        row[key]=0;
 }`</br>
Perhaps it is not the best solution, but it makes my logic work somehow. I hope the issue will be fixed soon.
