### ISSUE TITLE
Merge optimized zeroPad() function

### ISSUE THREAD

**Issue by vlasky** [nevill/zongji#58]
Can we please merge @jmealo's optimized zeroPad() function to replace the current version in lib/common.js:

https://github.com/nevill/zongji/pull/19/commits/0a6e7e78d66d970751b5a06505974d0fc5471f11

**Comment by numtel** [comment]
You're going to have to make a case for why.

https://jsperf.com/zongji-zeropad

**Comment by jmealo** [comment]
@numtel: https://jsperf.com/ways-to-0-pad-a-number/34 At the time I made that pull request, V8 was doing a much better job of optimizing the proposed version.

**Comment by vlasky** [comment]
@numtel and @jmealo thanks for your comments - they are very enlightening!

Having read the above, my understanding of the situation is that V8's optimization has improved since jmealo first measured the 3.5x performance benefit from his previously proposed alternative zeroPad() function and today the currently adopted zeroPad() implementation in Zongji is the better performing one.

My motivation for further optimization gains is our use of the [Meteor framework](https://guide.meteor.com/) which is heavily based on reactive data sources. If you've been following Meteor discussions, the big area of FUD are questions over the scalability of the underlying reactivity implementations, i.e. for MongoDB (the bundled database), MySQL and other data stores.

@wj32 and I have been continuing numtel's excellent work on [meteor-mysql](https://github.com/numtel/meteor-mysql) and [mysql-live-select](https://github.com/numtel/mysql-live-select) with my forks [here](https://github.com/vlasky/meteor-mysql) and [here](https://github.com/vlasky/mysql-live-select) aimed at achieving further usability and scalability improvements.

I note that as of today, the latest version of Meteor is 1.4.2.3 which still uses Node.js 4 that bundles an older version of V8, so it could still be possible that jmealo's code could be faster under that version, however the Meteor Development Group (MDG) have announced that Node.js V6 support is coming soon so its probably not worth being concerned about it.

**Comment by jmealo** [comment]
@numtel: I think that we should close this. V8 optimization hacks are a moving target. I haven't looked at the flame graphs for zongji in a while and I myself cannot defend merging my proposed changes at this point. The fastest `zeropad` in Javascript would make most developers eyes roll so I won't be creating a PR for that anytime soon :)
