### ISSUE TITLE
[Question] Zongji Usage on Slave

### ISSUE THREAD

**Issue by hodorswit** [nevill/zongji#66]
I'm trying to find a way to get real-time row events from a slave's relay log. Due to third party access controls, I do not have the ability to connect directly to the master. 

Looking at the code for this library, the binlogName is derived from `SHOW BINARY LOGS` which in my case will not contain the events being replicated by the master, but only events initiated on the slave. All of the master replication row events are stored in the *-relay-log.00000X files on the slave server. 

I'm thinking that because the relay log is in the same format as the binary log, it should be parsable by zongji with a bit of tweaking. i.e. specifying a configuration option for SLAVE and then retrieving the binLogName from `SHOW SLAVE STATUS`. 

My question: is there something inherently wrong with this approach? Is my understanding of the MASTER/SLAVE and their associated binlog files correct? I'm relatively new to MySQL and want to make sure I'm not missing something obvious. 

I'd be happy to submit a PR if my understanding of the problem is correct.

**Comment by hodorswit** [comment]
It looks like the --log-slave-updates configuration property is the secret sauce I've been looking for. https://dev.mysql.com/doc/refman/5.7/en/replication-options-slave.html 

In case anyone has the need in the future, you can set the log-slave-updates property on the slave, and all replicated row events from the master will be included in the slave's local bin-log in addition to the relay-log.

**Comment by nevill** [comment]
In fact, I have no idea about relay log. But if you want to reuse the parser, it would be nice to extract it out and build another new npm package.

**Comment by Midex26** [comment]
Hello @robbiedhickey ! I'm also trying to access slave logs with SHOW RELAYLOG EVENTS ! Have you any clue on how to do it ? I know this issue is old i'm sorry :'(
