### ISSUE TITLE
The server closed the connection.

### ISSUE THREAD

**Issue by shtse8** [nevill/zongji#73]
I want to use the latest version of zongji, but I can see the last release is already half year ago.
Any plan to release a new version? I keep getting ` The server closed the connection.` for version 0.4.4.

**Comment by shtse8** [comment]
I am trying the master branch.
But even I put `Pool` into ZongJi constructor, error is thrown:
```
Error: connect ECONNREFUSED 127.0.0.1:3306
```

I have checked it is due to cannot match the instance type Pool
here is my code:
```

let pool = mysql.createPool({
      connectionLimit : 10,
      host     : '10.138.0.7',
      user     : 'cmpool',
      password : 'Ohcepmam712',
      database : 'CMPool'
    })

    let zongji = new ZongJi(pool);
```

**Comment by shtse8** [comment]
Once my pool object is passed into the constructor, `instanceof Pool` becomes `false`.
it's true in my scoping for `var Pool = require('mysql/lib/Pool');`

**Comment by shtse8** [comment]
請問有人嗎?

**Comment by rodrigogs** [comment]
I fixed this in my fork: https://github.com/rodrigogs/zongji

**Comment by nevill** [comment]
I think this issue is fixed now.
