### ISSUE TITLE
先赞一个,请教如何知道当前那个库,哪个表,进行这增删改的操作,

### ISSUE THREAD

**Issue by 564064202** [nevill/zongji#74]
先赞一个,请教如何知道当前那个库,哪个表,进行这增删改的操作,需要将这些表的redis缓存直接干掉.
zongji.on('binlog', function(evt) {

}

evt没有文档说明,不知道什么意思

**Comment by RifeWang** [comment]
你需要自己封装一下返回结果，类似于以下数据：https://github.com/RifeWang/zongji/blob/master/lib/binlog_event.js#L23~L28，
也可以试试我封装过的 [zongji2](https://github.com/RifeWang/zongji)
