### ISSUE TITLE
Will zongji support MariaDB?

### ISSUE THREAD

**Issue by jmhemadri** [nevill/zongji#77]
Hi Team,

I am using MariaDB which comes by default from CentOS 7. Zongji not reading Events but it is working fine in another server which is having MySQL.

Thanks

**Comment by icodeforlove** [comment]
I have had no issues with zongi, and mariadb.

**Comment by nevill** [comment]
I don't think we are going to support MariaDB officially.

**Comment by icodeforlove** [comment]
@nevill any reason for this?

**Comment by ideiasfrescas** [comment]
@nevill I would like to also know why not support MariaDB officially.
