### ISSUE TITLE
Release last version [0.4.5]

### ISSUE THREAD

**Issue by AntonZarutsky** [nevill/zongji#78]
Hi @nevill. I'm very curios of using library with connection pool. Unfortunately npm /yarn repos have 0.4.4 as latest.
Can you release last version?

**Comment by numtel** [comment]
Until it's updated, you can use the github url in your package.json.

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

At the current master head:

```
git+https://github.com/nevill/zongji#81e94150bce89ad247b272c15ffd48f382c966d4
```

**Comment by nevill** [comment]
It's just released !
