### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by sctaix** [nevill/zongji#79]
my.cnf

[mysqld]
server-id        = 1
binlog_format    = row
log-bin          = mysql-bin

#binlog_do_db     = test
expire_logs_days = 10          # Optional, purge old logs
max_binlog_size  = 100M        # Optional, limit log size

then 

GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'repl'@'localhost'

now, just run one instance works perfect!

but, run two different instances at the same time, It does not working properly.

any idea?

**Comment by numtel** [comment]
See readme, each zongji instance must have unique `serverId`

**Comment by numtel** [comment]
From readme:

Option Name | Type | Description
------------|------|-------------------------------
`serverId`  | `integer` | [Unique number (1 - 2<sup>32</sup>)](http://dev.mysql.com/doc/refman/5.0/en/replication-options.html#option_mysqld_server-id) to identify this replication slave instance. Must be specified if running more than one instance of ZongJi. Must be used in `start()` method for effect.<br>**Default:** `1`




Add the option in the `start()` method. The MySQL server has a server id, then each ZongJi instance is acting like a MySQL server so it must also have a server id.

https://github.com/nevill/zongji/blob/master/example.js#L16


```js
zongji.start({
  includeEvents: ['tablemap', 'writerows', 'updaterows', 'deleterows'],
  serverId: 1234
});
```

**Comment by JayDadhania** [comment]
@sctaix Did this solve your issue? I'm having the same problem even after giving different serverId to each instance.
