### ISSUE TITLE
npm上的版本不可用

### ISSUE THREAD

**Issue by joyqi** [nevill/zongji#8]
请尽快更新一个可用版本到npm上，我目前只能引用源代码。npm上的0.2.0版本是无法启动的

**Comment by nevill** [comment]
等解决了 #7 以后就会上一个版本了，有兴趣帮我解决么？ @joyqi :smiling_imp:

**Comment by joyqi** [comment]
@nevill 我看了 #7 的问题，似乎已经解决了?

**Comment by nevill** [comment]
@joyqi I have published 0.2.1 package as a fixed version of 0.2.0. (with the old interface, but has less event types supported)

Also I have published 0.3.0, which you may have more interests to test with. Big thanks to @numtel for the efforts he made!
