### ISSUE TITLE
vulnerability on mysql

### ISSUE THREAD

**Issue by bidva** [nevill/zongji#82]
npm audit returns this vulnerability , Do you think it's fine to update mysql package to >=2.14.0?

> 
>                        === npm audit security report ===
> 
> ┌──────────────────────────────────────────────────────────────────────────────┐
> 
> │                                Manual Review                                 │
> │            Some vulnerabilities require your attention to resolve            │
> │                                                                              │
> │         Visit https://go.npm.me/audit-guide for additional guidance          │
> └──────────────────────────────────────────────────────────────────────────────┘
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Moderate      │ Remote Memory Exposure                                       │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ mysql                                                        │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Patched in    │ >=2.14.0                                                     │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ zongji                                                       │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ zongji > mysql                                               │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://nodesecurity.io/advisories/602                       │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 
> [!] 1 vulnerability found - Packages audited: 68 (56 dev, 0 optional)
>     Severity: 1 Moderate

**Comment by nevill** [comment]
Well, audit is a new feature of npm@6, but I'm still using npm@5. Anyway, I think it's safe to update as long as it can pass all the tests.

**Comment by nevill** [comment]
It's updated in v0.4.5
